### ISSUE TITLE
Maven Repository

### ISSUE THREAD

**Issue by turt2live** [kangarko/Rush#5]
Any plans for publishing this somewhere in the near future? If not, I do intend to fork and publish to my own so I can get started on writing library code for my plugins against Rush.

**Comment by Ekranos** [comment]
Maybe this could be a good alternative to use right now: https://jitpack.io/#kangarko/Rush/

**Comment by turt2live** [comment]
Closing due to age (project appears inactive)

**Comment by kangarko** [comment]
True, I stopped maintaining it years ago when other priorities came. Basically with seven active plugins, job, school etc. I had to make some cuts and that was one of it. Thank you for your understanding.

**Comment by turt2live** [comment]
No problem :) I'm just trimming down my open issues list to make it more manageable.
